### ISSUE TITLE
List of "matches" in manifest doesn't cover every form of the URL's used

### ISSUE THREAD

**Issue by StewMcc** [xnivaxhzne/hide-prime-xray#1]
List of "matches" in manifest doesn't cover every form of the URL's used

In the UK, adding `https://www.amazon.co.uk/gp/video/storefront/*` to the matches list allows it to work. Assume other regions will require the same. Seems the `https://www.primevideo.com/detail/*` is not used everywhere.

Might be worth calling out in the readme as side-loaded anyway.

However, I think this could be implemented in stylus https://chromewebstore.google.com/detail/clngdbkpkpeebahjckkjfobafhncgmne as just a style override instead though which might be easier for people. This did help me find the required element to hide though so thank you. e.g. write style with:

```
.xrayQuickView {
    visibility: hidden !important;
}
```

**Comment by xnivaxhzne** [comment]
@StewMcc addressed the issue. Yes, this will be a over kill for the problem. [stylus](https://chromewebstore.google.com/detail/clngdbkpkpeebahjckkjfobafhncgmne) does the job pretty neatly.
